[package]
name = 'iani'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'
authors = ["Brett Gilio <bgilio@kumc.edu>"]
description = "What the package does (one paragraph)."
license = "MIT"

[lib]
crate-type = [ 'staticlib' ]
name = 'iani'

[dependencies]
extendr-api = '*'
